### ISSUE TITLE
Can't connect to multiple servers

### ISSUE THREAD

**Issue by TheInitializer** [dkter/weecent#1]
When I try, weechat becomes really laggy to the point where it's unusable. Not really sure how to fix this.

###### why does weechat not support python 3 so I can use asyncio

**Comment by TheInitializer** [comment]
also I accidentally deleted the old repo so @heyitsmeuralex your comment is gone :(

I still have it in an open tab, so here's what you said:

>As a workaround, you can only have a websocket open to the current buffer's server at once, and for all others poll `/api/channel-list?sessionID=` to figure out if you have any unread notifications in a particular channel.

Then I said

>I guess that could work - closing and opening websockets every time the user switches buffers seems like it would be slow though 🤔

**Comment by bates64** [comment]
>accidentally deleted

...Github forces you to type in the name of the repo before allowing you to kill it :shipit: 🤔

**Comment by TheInitializer** [comment]
ok, maybe it wasn't entirely accidental. I deleted the repo, thinking it would fix a problem I was having. It didn't 📦

...computers are hard

**Comment by TheInitializer** [comment]
update: I made it so weechat is now usable when connecting to multiple servers! it's slow, and you can't receive messages in weecent, but it works and you can send messages.

when two servers are loaded, core fills up with 10000+ of these error messages:

```
11:25 python: stdout/stderr: Traceback (most recent call last):
11:25 python: stdout/stderr:   File "/home/david/.weechat/python/weecent.py", line 89, in timer_cb
11:25 python: stdout/stderr:     message_data = xd[server]['socket'].recv()
11:25 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 293, in recv
11:25 python: stdout/stderr:     opcode, data = self.recv_data()
11:25 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 310, in recv_data
11:25 python: stdout/stderr:     opcode, frame = self.recv_data_frame(control_frame)
11:25 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 323, in recv_data_frame
11:25 python: stdout/stderr:     frame = self.recv_frame()
11:25 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 357, in recv_frame
11:25 python: stdout/stderr:     return self.frame_buffer.recv_frame()
11:25 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_abnf.py", line 340, in recv_frame
11:25 python: stdout/stderr:     self.recv_header()
11:25 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_abnf.py", line 288, in recv_header
11:25 python: stdout/stderr:     header = self.recv_strict(2)
11:25 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_abnf.py", line 375, in recv_strict
11:25 python: stdout/stderr:     bytes_ = self.recv(min(16384, shortage))
11:25 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 427, in _recv
11:25 python: stdout/stderr:     return recv(self.sock, bufsize)
11:25 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_socket.py", line 80, in recv
11:25 python: stdout/stderr:     bytes_ = sock.recv(bufsize)
11:25 python: stdout/stderr:   File "/usr/lib/python2.7/ssl.py", line 756, in recv
11:25 python: stdout/stderr:     return self.read(buflen)
11:25 python: stdout/stderr:   File "/usr/lib/python2.7/ssl.py", line 643, in read
11:25 python: stdout/stderr:     v = self._sslobj.read(len)
11:25 python: stdout/stderr: ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:1754)
11:25 =!= python: error in function "timer_cb"
```

**Comment by bates64** [comment]
fantastic

**Comment by TheInitializer** [comment]
correction: not 10000+ error messages, 10000+ lines. the error message is 26 lines. 10000 / 26 = 384.615384615, so I'm getting 384.615384615+ error messages.
