### ISSUE TITLE
Occasionally spams core with error messages

### ISSUE THREAD

**Issue by TheInitializer** [dkter/weecent#3]
```
17:02 python: stdout/stderr: Traceback (most recent call last):
17:02 python: stdout/stderr:   File "/home/david/.weechat/python/weecent.py", line 129, in timer_cb
17:02 python: stdout/stderr:     message_data = xd[server]['socket'].recv()
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 293, in recv
17:02 python: stdout/stderr:     opcode, data = self.recv_data()
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 310, in recv_data
17:02 python: stdout/stderr:     opcode, frame = self.recv_data_frame(control_frame)
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 323, in recv_data_frame
17:02 python: stdout/stderr:     frame = self.recv_frame()
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 357, in recv_frame
17:02 python: stdout/stderr:     return self.frame_buffer.recv_frame()
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_abnf.py", line 340, in recv_frame
17:02 python: stdout/stderr:     self.recv_header()
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_abnf.py", line 288, in recv_header
17:02 python: stdout/stderr:     header = self.recv_strict(2)
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_abnf.py", line 375, in recv_strict
17:02 python: stdout/stderr:     bytes_ = self.recv(min(16384, shortage))
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 427, in _recv
17:02 python: stdout/stderr:     return recv(self.sock, bufsize)
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_socket.py", line 77, in recv
17:02 python: stdout/stderr:     raise WebSocketConnectionClosedException("socket is already closed.")
17:02 python: stdout/stderr: websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
17:02 =!= python: error in function "timer_cb"
17:02 python: stdout/stderr: Traceback (most recent call last):
17:02 python: stdout/stderr:   File "/home/david/.weechat/python/weecent.py", line 129, in timer_cb
17:02 python: stdout/stderr:     message_data = xd[server]['socket'].recv()
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 293, in recv
17:02 python: stdout/stderr:     opcode, data = self.recv_data()
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 310, in recv_data
17:02 python: stdout/stderr:     opcode, frame = self.recv_data_frame(control_frame)
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 323, in recv_data_frame
17:02 python: stdout/stderr:     frame = self.recv_frame()
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 357, in recv_frame
17:02 python: stdout/stderr:     return self.frame_buffer.recv_frame()
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_abnf.py", line 340, in recv_frame
17:02 python: stdout/stderr:     self.recv_header()
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_abnf.py", line 288, in recv_header
17:02 python: stdout/stderr:     header = self.recv_strict(2)
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_abnf.py", line 375, in recv_strict
17:02 python: stdout/stderr:     bytes_ = self.recv(min(16384, shortage))
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 427, in _recv
17:02 python: stdout/stderr:     return recv(self.sock, bufsize)
17:02 python: stdout/stderr:   File "/usr/local/lib/python2.7/dist-packages/websocket/_socket.py", line 77, in recv
17:02 python: stdout/stderr:     raise WebSocketConnectionClosedException("socket is already closed.")
17:02 python: stdout/stderr: websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
17:02 =!= python: error in function "timer_cb"
```

not sure why this is happening. weecent keeps working fine after this

**Comment by TheInitializer** [comment]
It seems to lag WeeChat while this is happening as well.

I wonder if I wrapped the `recv()` call in a try/except if it would also resolve #1 🤔

**Comment by TheInitializer** [comment]
nope 😛 not sure what I was expecting...

it does make weechat slightly more usable than in #1, but still definitely not ideal.
